New secret objective system
jacob-sahl/red-herring pull request #42
Opened 2022-10-18 14:59 UTC by jacob-sahl

This PR includes changes to several files but primarily LevelManager.cs and SecretObjective.cs

2022-10-18 15:25 UTC, TongkunZhang requested changes

2022-10-18 15:25 UTC, TongkunZhang commented on Assets/Scripts/Puzzles/SecretObjective.cs
> +  InvertTypewriter
If we combine all the secret objectives, how do we randomize them at the beginning of the round since some objectives depend on a certain puzzle?

2022-10-18 15:25 UTC, TongkunZhang commented on Assets/Scripts/Puzzles/LevelManager.cs
> +    gameController = GameObject.Find("GameController").GetComponent<GameController>();
Same

2022-10-19 01:24 UTC, jacob-sahl commented on Assets/Scripts/PlayerController.cs
> +    gameController = GameObject.Find("GameController").GetComponent<GameController>();
changed

2022-10-19 02:05 UTC, TongkunZhang approved these changes

2022-10-19 02:11 UTC, merged